id: P005463
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181192
  title: ཆོས་འབྱུང་ནོར་བུའི་མེ་ལོང་སོགས།
  author: ''
  volumes:
    1b16e1c40886442dabf8ba37ee268c22:
      image_group_id: I1KG16375
      title: ''
      volume_number: 1
      total_pages: 69
      base_file: v001.txt
