id: I3B6F4B42
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:06:35+00:00'
last_modified: '2022-06-08T03:15:48.943780+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181192
  title: ཆོས་འབྱུང་ནོར་བུའི་མེ་ལོང་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4891':
      image_group_id: I1KG16375
      title: ''
      total_pages: 69
      order: 1
      base_file: 4891.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
